name: tteewwkkrr
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.1.8
  http: ^1.1.0
  provider: ^6.0.5
  universal_html: ^2.2.1
  package_info_plus: ^4.0.2
  shared_preferences: ^2.1.0
  icons_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.0.0

flutter:
  uses-material-design: true
